name: gh-pages javadocs
on:
  push:
    branches:
      - master

jobs:
  build:
    name: gh-pages javadocs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven and uber-jar profile
        run: mvn clean package -Puber-jar
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: uber-jar
          path: target/*.jar
      - name: Build javadocs with Maven
        run: mvn javadoc:javadoc -Ddoclint=none -DexcludePackageNames=micycle.peasygradients.utilities
      - name: Publish javadocs
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: target/site/apidocs
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
